export type Book = {
  id: string; title: string; subtitle?: string; author: string; language: 'English' | 'Urdu' | 'Arabic' | 'Persian' | 'Latin' | 'Multiple'; era: string; century: string; topicTags: string[]; regionTags: string[]; sourceName: string; sourceUrl: string; license: string; pdfUrl?: string; epubUrl?: string; textUrl?: string; coverImage: string; description: string; aiSummary: string; tableOfContents: string[]; relatedPeople: string[]; relatedPlaces: string[]; relatedEvents: string[]; readingOrder: number; metadataOnly?: boolean;
};
export type Topic = {
  id: string; title: string; slug: string; alternateNames: string[]; type: string; era: string; region: string; summary: string; storyModeText: string[]; timeline: { date: string; title: string; description: string }[]; relatedBooks: string[]; relatedPeople: string[]; relatedPlaces: string[]; relatedImages: string[]; relatedMaps: string[]; citations: { label: string; url: string; type: 'Primary source' | 'Secondary source' | 'Reference' }[];
};
export type ImageAsset = { id: string; title: string; imageUrl: string; sourceUrl: string; creator: string; license: string; attribution: string; relatedTopic: string; relatedPlace: string; type: string };
export type Place = { id: string; name: string; currentCountry: string; historicalRegion: string; latitude: number; longitude: number; description: string; relatedBooks: string[]; relatedEvents: string[] };
export type Person = { id: string; name: string; alternateNames: string[]; birthYear?: number; deathYear?: number; region: string; role: string; biography: string; relatedBooks: string[]; relatedEvents: string[]; relatedPlaces: string[] };

const covers = ['#d7a94b','#a9693d','#274869','#62502d','#6b2535','#315142'];
const makeCover = (i: number, title: string) => `data:image/svg+xml,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="420" height="620"><rect width="100%" height="100%" fill="${covers[i%covers.length]}"/><path d="M35 42h350v536H35z" fill="none" stroke="#fff8e8" stroke-width="8" opacity=".55"/><path d="M70 90h280M70 125h220M70 490h280" stroke="#fff8e8" stroke-width="6" opacity=".7"/><text x="210" y="285" text-anchor="middle" font-family="Georgia" font-size="34" fill="#fff8e8">${title.replace(/&/g,'and').slice(0,34)}</text><text x="210" y="335" text-anchor="middle" font-family="Georgia" font-size="18" fill="#fff8e8">Bayt al-Tareekh Metadata</text></svg>`)}`;

const bookSeeds = [
['tabari-1','The History of al-Tabari, Vol. 1','Al-Tabari','English','Islamic History','9th–10th c.',['Islamic History','Caliphate','Primary chronicle'],['Middle East'],'Internet Archive','https://archive.org/search?query=History+of+al-Tabari','Source-linked metadata; verify volume rights before hosting','Universal history chronicle in translation; metadata links to public catalog/search pages.'],
['ibn-battuta','The Travels of Ibn Battuta','Ibn Battuta / H. A. R. Gibb','English','Medieval World','14th c.',['Travelers','Islamic World','Rihla'],['Morocco','India','China'],'Internet Archive','https://archive.org/search?query=Travels+of+Ibn+Battuta+Gibb','Public-domain/open catalog links where available','Classic travel account documenting cities, courts and routes across the medieval Islamic world.'],
['muqaddimah','The Muqaddimah','Ibn Khaldun','English','Historiography','14th c.',['Historians','Sociology','Maghrib'],['North Africa'],'Internet Archive','https://archive.org/search?query=Ibn+Khaldun+Muqaddimah','Source-linked metadata; edition rights vary','Foundational work on history, society, dynasties and civilization.'],
['muir-caliphate','The Caliphate: Its Rise, Decline, and Fall','William Muir','English','Islamic History','19th c.',['Caliphate','Umayyads','Abbasids'],['Middle East'],'Project Gutenberg','https://www.gutenberg.org/ebooks/search/?query=caliphate+muir','Public domain in many jurisdictions; verify locally','Older secondary history useful for comparison with modern scholarship.'],
['lane-arabian','Arabian Society in the Middle Ages','Edward William Lane','English','Medieval Islamic civilization','19th c.',['Society','Medieval','Arabic sources'],['Egypt','Arabia'],'Project Gutenberg','https://www.gutenberg.org/ebooks/search/?query=Arabian+Society+Middle+Ages','Public domain','A public-domain window into translated medieval Arabic social material.'],
['masudi','Meadows of Gold','Al-Masudi','English','Islamic History','10th c.',['Historians','Geography','Abbasids'],['Middle East'],'Internet Archive','https://archive.org/search?query=Meadows+of+Gold+Masudi','Metadata only; verify edition rights','Medieval Arabic historical-geographical source associated with the Abbasid age.'],
['baladhuri','Futuh al-Buldan','Al-Baladhuri','English','Islamic History','9th c.',['Conquests','Primary source','Caliphate'],['Middle East','Persia'],'Internet Archive','https://archive.org/search?query=Futuh+al-Buldan','Metadata only; verify edition rights','Important early Arabic source for conquests and administrative history.'],
['gibbon-rome','The History of the Decline and Fall of the Roman Empire','Edward Gibbon','English','Ancient History','18th c.',['Rome','Byzantium','Secondary source'],['Mediterranean'],'Project Gutenberg','https://www.gutenberg.org/ebooks/25717','Public domain','Classic public-domain secondary work; best read critically with modern scholarship.'],
['herodotus','The Histories','Herodotus','English','Ancient History','5th c. BCE',['Greece','Persia','Primary source'],['Mediterranean','Persia'],'Project Gutenberg','https://www.gutenberg.org/ebooks/2707','Public domain','Ancient Greek historical source for Persian wars and wider ethnographic material.'],
['marco-polo','The Travels of Marco Polo','Marco Polo','English','Medieval World','13th c.',['Travelers','Silk Road','Mongols'],['Central Asia','China'],'Project Gutenberg','https://www.gutenberg.org/ebooks/10636','Public domain','Travel narrative relevant to Mongol-era Eurasia and trade routes.'],
['urdu-tareekh-islam','Tareekh-e-Islam catalog record','Multiple Urdu authors','Urdu','Islamic History','Multiple',['Urdu','Islamic History'],['Middle East','South Asia'],'Rekhta / Internet Archive search','https://archive.org/search?query=title%3A%28Tareekh-e-Islam%29','Metadata only — do not host until rights verified','Urdu Islamic history metadata placeholder for legal source connection.'],
['urdu-ibn-khaldun','Muqaddima Ibn Khaldun Urdu catalog record','Ibn Khaldun / translators','Urdu','Historiography','14th c.',['Urdu','Historians'],['North Africa','South Asia'],'Archive catalog search','https://archive.org/search?query=Muqaddima+Ibn+Khaldun+Urdu','Metadata only — rights vary','Urdu-access placeholder linking users to catalog discovery.'],
['plutarch-lives','Plutarch Lives','Plutarch','English','Ancient Biography','1st–2nd c.',['Biography','Alexander','Caesar','Great personalities'],['Greece','Rome'],'Project Gutenberg','https://www.gutenberg.org/ebooks/search/?query=Plutarch+Lives','Public domain editions available','Parallel biographies of Greek and Roman figures; useful for personality studies with source caveats.'],
['homer-iliad','The Iliad','Homer','English','Ancient Epic Tradition','8th c. BCE tradition',['Legend','Troy','Achilles','Epic'],['Aegean','Anatolia'],'Project Gutenberg','https://www.gutenberg.org/ebooks/2199','Public domain','Epic tradition around Troy; displayed as literature/legend, not simple factual chronicle.'],
['homer-odyssey','The Odyssey','Homer','English','Ancient Epic Tradition','8th c. BCE tradition',['Legend','Odysseus','Journey','Epic'],['Mediterranean'],'Project Gutenberg','https://www.gutenberg.org/ebooks/1727','Public domain','Ancient travel-and-return epic for a clearly labeled legends and story tradition section.'],
['mahabharata','The Mahabharata','Vyasa / translated editions','English','Ancient Indian Epic Tradition','Ancient tradition',['India','Legend','Epic','Dharma'],['South Asia'],'Project Gutenberg','https://www.gutenberg.org/ebooks/search/?query=Mahabharata','Public domain editions available','Major South Asian epic tradition; presented respectfully as literary/sacred tradition with genre labels.'],
['ramayana','The Ramayana','Valmiki / translated editions','English','Ancient Indian Epic Tradition','Ancient tradition',['India','Legend','Rama','Epic'],['South Asia'],'Project Gutenberg','https://www.gutenberg.org/ebooks/search/?query=Ramayana','Public domain editions available','Epic tradition of exile, conflict and return; source genre is clearly labeled.'],
['gilgamesh','Epic of Gilgamesh catalog metadata','Ancient Mesopotamian tradition','English','Ancient Mesopotamia','2nd millennium BCE tradition',['Mesopotamia','Legend','Gilgamesh','Epic'],['Iraq'],'Internet Archive','https://archive.org/search?query=Epic+of+Gilgamesh','Metadata only — translation rights vary','Ancient Mesopotamian epic metadata for literature, myth and memory study.'],
['xenophon-anabasis','Anabasis','Xenophon','English','Ancient Greek and Persian History','4th c. BCE',['Persia','Greece','Soldiers','Primary source'],['Persia','Anatolia'],'Project Gutenberg','https://www.gutenberg.org/ebooks/search/?query=Xenophon+Anabasis','Public domain editions available','A dramatic primary-source march through Persian imperial geography.'],
['caesar-commentaries','The Commentaries of Julius Caesar','Julius Caesar','English','Roman Republic','1st c. BCE',['Rome','Gaul','Primary source','Caesar'],['Rome','Gaul'],'Project Gutenberg','https://www.gutenberg.org/ebooks/search/?query=Julius+Caesar+Commentaries','Public domain editions available','First-person Roman political and military text, read critically as self-presentation.'],
['tacitus-annals','The Annals','Tacitus','English','Roman Empire','1st–2nd c.',['Rome','Emperors','Primary source'],['Mediterranean'],'Project Gutenberg','https://www.gutenberg.org/ebooks/search/?query=Tacitus+Annals','Public domain editions available','Roman imperial narrative source for emperors, politics and court drama.'],
['baburnama','Baburnama catalog metadata','Babur','English','Mughal India','16th c.',['Mughal','India','Memoir','Great personalities'],['South Asia'],'Internet Archive','https://archive.org/search?query=Baburnama','Metadata only — verify edition rights','Memoir source metadata for Babur, gardens, battles and early Mughal history.'],
['arabian-nights','The Arabian Nights metadata','Traditional / translated editions','English','Medieval Story Tradition','Medieval',['Arabic literature','Legend','Story worlds'],['Middle East','Persia','India'],'Project Gutenberg','https://www.gutenberg.org/ebooks/search/?query=Arabian+Nights','Public domain editions available','Story tradition for culture and imagination; not presented as factual chronicle.']
];
const moreTitles = ['Abbasid Baghdad Reader','Ottoman Source Reader','Mughal India Bibliography','Al-Andalus Reading Path','House of Wisdom Studies','Salahuddin and the Ayyubids','Crusades Multi-Source Packet','Ancient Egypt Public Texts','Persian Empire Sourcebook','Indus Valley Archaeology Notes','Silk Road Travel Sources','Mongol Empire Reader','Byzantine and Islamic Frontiers','Mamluk Cairo Archive','Seljuk Anatolia Studies','Islamic Golden Age Science','Urdu World History Catalog','Urdu Muslim Scientists Catalog','Arabic Manuscript Studies','Persian Chronicles Catalog','Ottoman Travel Accounts','Medieval Cities Reader','Trade Routes and Pilgrimage','Coins and Inscriptions Guide','Architecture of Islamic Cities','Ancient Mesopotamia Texts','Ancient China Historical Sources','Greek and Roman Crossroads','Fatimid Cairo Studies','Safavid Iran Reader','Central Asian Scholars','Ibn Sina Source Guide','Al-Biruni Source Guide','Al-Khwarizmi Source Guide','Rumi and Persian Literary Worlds','Baburnama Source Metadata','Akbarnama Source Metadata','Delhi Sultanate Reader'];
export const books: Book[] = [
...bookSeeds.map((b, i) => ({ id:b[0] as string, title:b[1] as string, author:b[2] as string, language:b[3] as Book['language'], era:b[4] as string, century:b[5] as string, topicTags:b[6] as string[], regionTags:b[7] as string[], sourceName:b[8] as string, sourceUrl:b[9] as string, license:b[10] as string, coverImage: makeCover(i,b[1] as string), description:b[11] as string, aiSummary:'AI-enhanced summary based on listed sources. This record summarizes catalog metadata and does not replace the original source.', tableOfContents:['Source record','Historical context','Reading notes','Citation guidance'], relatedPeople:[], relatedPlaces:[], relatedEvents:[], readingOrder:i+1, metadataOnly:(b[10] as string).includes('Metadata') || (b[10] as string).includes('metadata') })),
...moreTitles.map((title, idx) => ({ id:`metadata-${idx+1}`, title, author:'Curated metadata team', language: idx%5===0?'Urdu':'English' as Book['language'], era: idx%3===0?'Islamic History':idx%3===1?'Medieval World':'Ancient History', century:'Multiple', topicTags:[title.split(' ')[0], 'Reading bundle candidate','Metadata'], regionTags:['Global'], sourceName:'Open library/catalog connection pending', sourceUrl:'https://archive.org/', license:'Metadata only — no PDF hosted until public-domain/open-license status is verified', coverImage: makeCover(idx+12,title), description:`Placeholder metadata record for ${title}. It is clearly marked metadata-only so the platform never pretends to host or own unverified books.`, aiSummary:'AI-enhanced summary based on listed sources. Pending curator approval and source verification.', tableOfContents:['Metadata checklist','Rights verification','Recommended sources'], relatedPeople:[], relatedPlaces:[], relatedEvents:[], readingOrder:idx+13, metadataOnly:true }))
];

export const topics: Topic[] = ['Abbasid Caliphate','Ottoman Empire','Mughal Empire','Al-Andalus','Ibn Battuta','Ibn Khaldun','Baghdad','House of Wisdom','Salahuddin Ayyubi','Mongol Empire','Crusades','Ancient Egypt','Roman Empire','Persian Empire','Indus Valley Civilization','Silk Road','Mesopotamia and Gilgamesh','Troy and the Homeric Epics','Alexander the Great','Ashoka and Mauryan India','Han Dynasty China','Hannibal Barca','Cleopatra VII','Hatshepsut','Zheng He','Al-Biruni','Al-Khwarizmi'].map((title, i) => ({
 id:`topic-${i+1}`, title, slug:title.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''), alternateNames: title==='Al-Andalus'?['Andalus','Muslim Spain']:title==='House of Wisdom'?['Bayt al-Hikma','Baghdad House Wisdom']:title==='Salahuddin Ayyubi'?['Saladin','Salah al-Din']: [title.replace('al-','')], type: i<10?'Islamic / Medieval':'Ancient / World', era: i<10?'Medieval':'Ancient to Medieval', region: ['Middle East','Anatolia','South Asia','Iberia','Afro-Eurasia','Maghrib','Iraq','Iraq','Levant','Eurasia','Mediterranean','Egypt','Mediterranean','Persia','South Asia','Eurasia'][i], summary: `${title} is presented as a source-based topic page with separated primary sources, secondary sources, AI-enhanced summaries, maps, images, citations and reading paths.`, storyModeText: ['Background: this section converts verified source notes into readable narration without pretending to be an original chronicle.','Rise and turning points: curators connect dates, people and places to books and citations before publication.','Legacy: readers are directed back to primary and secondary sources for deeper study.'], timeline: [{date:i<10?'750 CE':'3000 BCE', title:`${title} context begins`, description:'Chronological anchor awaiting curator expansion.'},{date:i<10?'1258 CE':'500 CE', title:`${title} later legacy`, description:'Timeline entry linked to bibliography and maps.'}], relatedBooks: books.slice(i, i+5).map(b=>b.id), relatedPeople: ['Al-Mansur','Harun al-Rashid','Al-Ma’mun','Ibn Battuta','Ibn Khaldun'].slice(0,3), relatedPlaces: ['Baghdad','Samarra','Damascus','Cairo','Cordoba'].slice(0,3), relatedImages: ['map-abbasid','manuscript-1'], relatedMaps: ['map-abbasid-expansion','silk-road-routes'], citations: [{label:'Internet Archive catalog search',url:'https://archive.org/',type:'Reference'},{label:'Project Gutenberg public-domain library',url:'https://www.gutenberg.org/',type:'Reference'}]
}));

export const images: ImageAsset[] = [
 {id:'manuscript-1',title:'Digitized manuscript folio placeholder',imageUrl:makeCover(1,'Manuscript'),sourceUrl:'https://commons.wikimedia.org/',creator:'Creator varies by item',license:'Use only open-license/public-domain images after verification',attribution:'Attribution required from source record',relatedTopic:'House of Wisdom',relatedPlace:'Baghdad',type:'Manuscript'},
 {id:'map-abbasid',title:'Historical map source placeholder',imageUrl:makeCover(2,'Map Archive'),sourceUrl:'https://commons.wikimedia.org/',creator:'Cartographer varies by item',license:'Open-license/public-domain only',attribution:'Verify per map record',relatedTopic:'Abbasid Caliphate',relatedPlace:'Baghdad',type:'Map'},
 {id:'architecture-1',title:'Islamic architecture image placeholder',imageUrl:makeCover(3,'Architecture'),sourceUrl:'https://www.metmuseum.org/art/collection',creator:'Museum record',license:'Follow source license',attribution:'Museum/source attribution required',relatedTopic:'Islamic Golden Age',relatedPlace:'Cairo',type:'Architecture'}
];
export const places: Place[] = [
 {id:'baghdad',name:'Baghdad',currentCountry:'Iraq',historicalRegion:'Abbasid Iraq',latitude:33.3152,longitude:44.3661,description:'Key Abbasid capital and manuscript/book culture hub.',relatedBooks:['tabari-1','masudi'],relatedEvents:['Abbasid foundation','Mongol sack of Baghdad']},
 {id:'cordoba',name:'Cordoba',currentCountry:'Spain',historicalRegion:'Al-Andalus',latitude:37.8882,longitude:-4.7794,description:'Major Andalusi city associated with learning, architecture and libraries.',relatedBooks:['metadata-4'],relatedEvents:['Umayyad Cordoba']},
 {id:'cairo',name:'Cairo',currentCountry:'Egypt',historicalRegion:'Fatimid and Mamluk Egypt',latitude:30.0444,longitude:31.2357,description:'Major Islamic metropolis, archive, mosque and manuscript center.',relatedBooks:['metadata-14'],relatedEvents:['Fatimid Cairo','Mamluk Sultanate']}
];
export const people: Person[] = [
 {id:'ibn-battuta',name:'Ibn Battuta',alternateNames:['Ibn Baṭṭūṭa'],birthYear:1304,deathYear:1369,region:'Morocco / Afro-Eurasia',role:'Traveler',biography:'Traveler whose Rihla is central to medieval world history reading paths.',relatedBooks:['ibn-battuta'],relatedEvents:['Rihla journeys'],relatedPlaces:['Tangier','Delhi','Cairo']},
 {id:'ibn-khaldun',name:'Ibn Khaldun',alternateNames:['Ibn Khaldūn'],birthYear:1332,deathYear:1406,region:'North Africa',role:'Historian',biography:'Historian and thinker associated with the Muqaddimah.',relatedBooks:['muqaddimah'],relatedEvents:['Composition of Muqaddimah'],relatedPlaces:['Tunis','Cairo']},
 {id:'al-biruni',name:'Al-Biruni',alternateNames:['Abu Rayhan al-Biruni'],birthYear:973,deathYear:1048,region:'Khwarazm, Ghazni and India',role:'Scholar and polymath',biography:'A great personality profile for astronomy, geography, languages and India studies; story mode should be source-linked and avoid exaggeration.',relatedBooks:['metadata-31'],relatedEvents:['Study of India','Astronomical measurements'],relatedPlaces:['Khwarazm','Ghazni','India']},
 {id:'al-khwarizmi',name:'Al-Khwarizmi',alternateNames:['Muḥammad ibn Mūsā al-Khwārizmī'],birthYear:780,deathYear:850,region:'Abbasid world',role:'Mathematician and astronomer',biography:'A source-based science personality connected with calculation, astronomy, geography and Baghdad scholarly networks.',relatedBooks:['metadata-32'],relatedEvents:['Abbasid scholarly movement'],relatedPlaces:['Baghdad']},
 {id:'hatshepsut',name:'Hatshepsut',alternateNames:['Maatkare Hatshepsut'],birthYear:-1507,deathYear:-1458,region:'Ancient Egypt',role:'Pharaoh',biography:'Ancient personality story combining kingship, monuments, trade expeditions and the politics of memory.',relatedBooks:['metadata-8'],relatedEvents:['Punt expedition'],relatedPlaces:['Thebes','Deir el-Bahri']},
 {id:'hannibal',name:'Hannibal Barca',alternateNames:['Hannibal'],birthYear:-247,deathYear:-183,region:'Carthage and Mediterranean',role:'General',biography:'His Alpine crossing and Italian campaign make a gripping story when Polybius, Livy and modern analysis are separated.',relatedBooks:['metadata-28'],relatedEvents:['Second Punic War'],relatedPlaces:['Carthage','Alps','Rome']},
 {id:'cleopatra',name:'Cleopatra VII',alternateNames:['Cleopatra Philopator'],birthYear:-69,deathYear:-30,region:'Ptolemaic Egypt',role:'Ruler',biography:'A personality page that separates Roman propaganda, later legend and political history in the age of Caesar and Antony.',relatedBooks:['metadata-8'],relatedEvents:['Fall of Ptolemaic Egypt'],relatedPlaces:['Alexandria','Rome']}
];
